// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { join } from "path";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: join("prisma", "schema.prisma"),
  migrations: {
    path: join("prisma", "migrations"),
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
